spring:
  application:
    name: Pharmacy-Service
  datasource:
    url: jdbc:mysql://mysql-db:3306/pharmacydb?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: ${DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  # kafka Config
  #Producer config
  kafka:
    enabled: ${KAFKA_ENABLED:false}   # Set KAFKA_ENABLED : true in Env to enable Kafka
    producer:
      bootstrap-server: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
    #Consumer Config
    consumer:
      bootstrap-server: localhost:9092
      group-id: group1
      auto-offset-reset: earliest
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: ${SERVER_PORT:8083}

secret:
  header:
    key: ${SECRET_HEADER_KEY}

# To-Do :- Make this eureka Configurable
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakers

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.I_care.Pharmacy_Service.entity





